version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hello"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        # Only run this job if build succeeds
        requires:
          - build
